### ISSUE TITLE
Ordering of intervals in RRA seems wrong

### ISSUE THREAD

**Issue by GabrieleCocco** [GrammarViz2/grammarviz2_src#40]
According to [a paper](http://www2.hawaii.edu/~senin/assets/papers/timeseries_grammaranomaly.pdf) the intervals in RRA should be ordered by increasing *Usage Frequency*, while in [findBestDiscordForInterval](https://github.com/GrammarViz2/grammarviz2_src/blob/master/src/main/java/net/seninp/grammarviz/anomaly/RRAImplementation.java#L134) they seem to be sorted based on coverage.

**Comment by GabrieleCocco** [comment]
Ok, possible explanation is the coverage set a bit counter-intuitively [here](https://github.com/GrammarViz2/grammarviz2_src/blob/master/src/main/java/net/seninp/grammarviz/GrammarVizAnomaly.java#L745)

**Comment by seninp** [comment]
actually, there are more than these two ways to apply heuristics ordering, in GUI I was experimenting with these five in addition to the rule frequency:

![heuristics for intervals ordering](https://raw.githubusercontent.com/GrammarViz2/grammarviz2_src/master/src/resources/issues/Issue40.png)

you may try these for your own application domain as the results (the performance) may vary significantly.

kudos for looking into the code!
