### ISSUE TITLE
description of the data files ?

### ISSUE THREAD

**Issue by vsraptor** [GrammarViz2/grammarviz2_src#51]
where can i find a description of the data files ?

**Comment by psenin-sanofi** [comment]
Hello -- if you mean input files, i.e. time-series, it's a single column text file. Just a sequence of numbers one per row. There are few examples in the project itself, folder data/.

**Comment by vsraptor** [comment]
i know .. i meant description of what is the file "meaning"
f.e. ecg_i.txt , I can understand is from ECG... but what about TEK.., mitdb.., nprs43..,ap1 ... etc

**Comment by seninp** [comment]
That is a good question. I don't remember the dataset's exact origins, sorry. TEK is the space shuttle data -- Eamonn Keogh's presentations online would have a lot of info on those. mitdb chfdb stdb ecg 3xx_signal... are from medical databases, various heart and breathing signals, grammarviz HTML site should have an example of querying those databases... not sure their conversion tool is still available and running. There also few GPS tracks unfolded into Hilbert curve... industrial and ICU signals.
Sorry, I don't have a table mapping file to the source. At some point I knew those by heart and never thought I'll forget.

**Comment by vsraptor** [comment]
thanks :(
